#!/usr/bin/env python3

import sys
from decimal import Decimal

readfile=sys.argv[1]
f=open(readfile,'r')
lines=f.readlines()

#print(lines)

tmplist=[]
for line in lines:
    words=line.split()
    words[1]=(int(words[1]))
    words[5]=(int(words[5]))
    for i in range (6, (len(words)-1)):
        words[i] = Decimal(words[i])
        #print(type(words[i]))
        #sys.exit()
    tmplist.append(words)
    
    #print(words)
    #sys.exit()

f.close()

#print(tmplist)

#what goes in the new pdb file?

f=open("tmp.out", 'w')
for tmp in tmplist:
    #print(type(tmp[0]))
    #sys.exit()
    #sent= "{}"
    #f.write(sent.format(tmp[0]))
    #print(tmp[1])
    #sys.exit()
    """
    if (tmp[1] < 10):
        #print(tmp[1])
        sent="{} {:-4}"
        #print(sent.format(tmp[1]))
        f.write(sent.format(tmp[0], tmp[1]))
    elif (tmp[1] < 100):
        sent="{} {:-4}"
        #print(sent.format(tmp[1]))
        f.write(sent.format(tmp[0], tmp[1]))
    elif (tmp[1] < 1000):
        sent="{} {:-4}"
        f.write(sent.format(tmp[0], tmp[1]))
    else:
        sent="{} {}"
        f.write(sent.format(tmp[0], tmp[1]))

    if (len(tmp[2]) < 2):
        sent="{:>4}"
        f.write(sent.format(tmp[2]))
    elif (len(tmp[2]) < 3):
        sent = "{:>4}"
        f.write(sent.format(tmp[2]))
    else:
        sent = "{:>4}"
        f.write(sent.format(tmp[2]))
    """
    sent="{} {:>4} {:>4} {:>4} {} {:>4} {:>5} {:>-7} {:>6} {} {:>5} {}\n"
    f.write(sent.format(tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11]))

    

    #sys.exit()

f.close()
sys.exit()
    
